language: generic

sudo: required

addons:
  apt:
    packages:
      - steghide
      - cargo
env:
  global:
    - PATH=/home/travis/.cargo/bin

after_success: |
  cargo install stegbrute &&
  stegbrute
