language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - 1.34.0
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo install stegbrute
  - stegbrute -h
notifications:
  email:
    on_success: never
