language: generic

sudo: required

addons:
  apt:
    packages:
      - steghide
      - cargo

after_success: |
  cargo install stegbrute &&
  echo 'export PATH="/home/travis/.cargo/bin:$PATH"' >> /etc/bash.bashrc &&
  stegbrute
